
spring:
  profiles:
    active: dev
  application:
    name: DESIERTO-ORDER-SERVICE
  data:
    mongodb:
     uri: mongodb://localhost:27017/orderdb
     host: localhost
     port: 27017
     database: orderdb
     repositories:
          enabled: true

